spring:
  redis:
    port: 6379
    host: 127.0.0.1
logging:
  level:
    root: info
    com.example.back.api.controller.log: trace
  file:
    path: logs
    name: logs/back.log
    max-size: 100MB
    max-history: 30
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"


